data_dir: "./data/FFHQ_testingsubset/"
output_dir: "./output/FFHQ_testingsubset/"
batch_size: 1
grad_accumulation: 1

model:
  num_gaussians: 1000
  input_dim: 8
  model_dim: 512

train:
  max_epochs: 2000
  base_lr: 0.00005      # 5e-5
  lr_warmup_epochs: 50
  kl_warmup_epochs: 500
  vis_warmup_epochs: 500
  sinkhorn_warmup_epochs: 200
  clip_norm: 2.5
  
  # Weights
  recon_weight: 10.0
  max_kl_weight: 0.1
  l1_weight: 0.1
  ssim_weight: 0.1

logging:
  sample_save_rate: 50
  reconstruct_save_rate: 25
  checkpoint_save_rate: 100