data_dir: "./data/FFHQ_testingsubset/"
output_dir: "./output/"
batch_size: 4
grad_accumulation: 2

model:
  num_gaussians: 1000
  input_dim: 8
  model_dim: 512

train:
  max_epochs: 2000
  base_lr: 0.00005      # 1e-4
  lr_warmup_epochs: 50
  kl_warmup_epochs: 500
  lpips_warmup_epochs: 1000
  sinkhorn_warmup_epochs: 200
  clip_norm: 2.5
  
  # Weights
  max_kl_weight: 1.0
  recon_weight: 0.1
  lpips_weight: 1000.0

logging:
  sample_save_rate: 50
  reconstruct_save_rate: 25